spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9002"
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: 1234
            authorization-grant-type: autorizathion_code
            redirect-uri: "http://127.0.0.1:9001/authorized"
            scope:
              - openid
              - profile
              - read
            client-name: client-app
        provider: 
          spring:
            issuer-uri: "http://127.0.0.1:9002"